pre-commit:
  parallel: true
  commands:
    prettier-format:
      tags:
        - formatter
      glob: "*.{md,yaml}"
      run: npx prettier --write {staged_files}
    ruff-format:
      tags:
        - formatter
      run: uv run ruff format
    ruff-check:
      tags:
        - fixer
      run: uv run ruff check --fix
